colorscheme twilight_lucas
set guifont=Inconsolata:h16

if has("gui_macvim")
  " Cmd+T to open Command-T
  macmenu &File.New\ Tab key=<nop>
  nmap <D-t> :CommandT<CR>
  imap <D-t> <Esc>:CommandT<CR>

  " Cmd+R to flush Command-T cache
  nmap <D-r> :CommandTFlush<CR>
  imap <D-r> <Esc>:CommandTFlush<CR>

  " Stop Cmd+W from closing window
  macmenu &File.Close key=<nop>
  nmap <D-w> :Closer<CR>
  imap <D-w> <Esc>:Closer<CR>

  menu File.Close\ Instance :qa<CR>
  inoremenu File.Close\ Instance :qa<CR>

  " Fullscreen
  set lines=100
  set columns=300

  " Transparency
  set transparency=1

  " Hide toolbar
  set guioptions=egmrt
endif

" Auto-NERDTree if root.
if argv(0) == '.'
  au VimEnter * :NERDTreeToggle
  au VimEnter * :wincmd p
endif

" Color columns
set cc+=80
hi ColorColumn guibg=#222222

" Set color column for features
autocmd BufWinEnter *.feature set cc+=11
autocmd BufWinLeave *.feature set cc-=11

let g:indent_guides_color_change_percent = 3
let g:indent_guides_enable_on_vim_startup = 1

" NERDCommenter extra spaces
let g:NERDSpaceDelims=1

" Command-T
let g:CommandTMaxFiles = 20000
let g:CommandTMaxHeight = 10
